### ISSUE TITLE
Feature Request: Enable/disable field tabs

### ISSUE THREAD

**Issue by Regaez** [mmikkel/Reasons-Craft#10]
Hey there! Would it be possible to enable/disable an entire field tab based on conditionals?

Thinking about how best to structure some context dependent fields for a site and grouping certain modules by tab and then toggling the tab would be handy.

**Comment by mmikkel** [comment]
For simplicity's sake, Reasons was designed to work on a tab-by-tab basis. Not to rule anything out, but there are quite a few features I'd like to add before looking at this – so don't count on this ever being implemented, sorry :)
