### ISSUE TITLE
Feature Request: Add Support for the "Button Box" field type plugin

### ISSUE THREAD

**Issue by richhayler** [mmikkel/Reasons-Craft#11]
Please could you add support for the "button box" plugin by SuperCoolDesign. Button Box would be a great candidate for this plugin as instead of a boring text toggle (e.g. dropdown, radio button or checkbox) Button Box provides the option to set images in place of radio buttons. 

http://plugins.supercooldesign.co.uk/plugin/button-box

**Comment by mmikkel** [comment]
Hey @richhayler, thanks for contributing. I'll see what I can do!

**Comment by richhayler** [comment]
Would love to see this feature implemented. Seems like a great combination.

**Comment by mmikkel** [comment]
Well it took me a good while, but full support for the Button Box fieldtypes is in version [1.0.6](https://github.com/mmikkel/Reasons-Craft/releases/tag/v.1.0.6). Thanks for contributing!
