### ISSUE TITLE
Does not work in Live Preview

### ISSUE THREAD

**Issue by johndwells** [mmikkel/Reasons-Craft#12]
I'm using a series of lightswitch fields to toggle the visibility of other text fields, but when I edit in Live Preview mode, they don't work.

**Comment by mmikkel** [comment]
Thanks for the heads up, @johndwells! I have to admit, I never tested Reasons in Live Preview (rarely use it..) :dancers:

**Comment by mmikkel** [comment]
Fixed in 0.2.2. Thanks for reporting!

**Comment by stiekstra** [comment]
It seems this issue has returned in version 1.0.2. Toggling a lightswitch in Live Preview doesn't toggle the visibility of other field.

**Comment by mmikkel** [comment]
Hey @stiekstra, thanks for reporting! This is unfortunate, I'm on it.

**Comment by mmikkel** [comment]
Hi @stiekstra, this issue should now be resolved with v. 1.0.3. Thanks again for reporting, and sorry for the inconvenience!

**Comment by stiekstra** [comment]
Works like a charm. Thanks @mmikkel!
