### ISSUE TITLE
Add Craft 2.5 support

### ISSUE THREAD

**Issue by mmikkel** [mmikkel/Reasons-Craft#14]
Reasons is markup dependent – the CP has been redesigned for Craft 2.5 and Reasons currently does not work on 2.5 builds.

**Comment by jonorherrington** [comment]
+1

**Comment by shealan** [comment]
Please +1

**Comment by mmikkel** [comment]
Thanks for your interest, guys.

2.5 support (and some other fixes and additional features) is incoming, some time this week. Scout's honor!

**Comment by shealan** [comment]
Fantastic! I would pay proper money to get this working inside matrix and supertable fields. Do you think this is possible or just an amazing dream?

**Comment by mildlygeeky** [comment]
I'd also be willing to sponsor development of it working in Matrix and SuperTable - love this plugin!

**Comment by vonsio** [comment]
Yeah I would pay as well a little for this plugin! Keep up the good work :+1:

**Comment by shealan** [comment]
Looks like we have a movement here. I would suggest @mmikkel consider releasing a commercial version?

![shut-up-and-take-my-money](https://cloud.githubusercontent.com/assets/74932/11458387/d2e39b74-96b6-11e5-817d-7ec5419216d1.jpg)

**Comment by mmikkel** [comment]
Again – thanks a lot for your interest in Reasons!

Apologize for keeping folks waiting, but I finally pushed 0.2.2 which should work in Craft 2.5.

Honestly, the actual 2.5 fix was really quite simple – the reason this took a while was that I've been working on adding support for all native element types (Categories, Assets, Tags, Global Sets, Users) and I really wanted to have that in for the 2.5 release. I hit a snag though, and have to refactor a lot of the code, so it'll be a little while longer before that makes it in.

The good thing about the refactor is that it should make it a lot easier to also add support for Matrix and Super Table, which is something a lot of people have been hoping to see.

Finally – I seriously appreciate the monetary offers made in this thread, though paid plugins isn't really my game and its very unlikely Reasons will ever be a commercial plugin. Sorry!
