### ISSUE TITLE
Text field trigger

### ISSUE THREAD

**Issue by akukral** [mmikkel/Reasons-Craft#16]
Is it possible to use a text field to trigger the display of another field via regular expression? I.E. Heading field contains /.*/ then show a subheading field.

**Comment by mmikkel** [comment]
Hello @akukral, thanks for contributing!

You can use Plain Text fields as triggers (toggle fields), but not with regular expressions matching. Unfortunately, it's not likely that this is a feature I will ever add, sorry.

However, if you just want to hide/show a field based on whether a Plain Text field is empty or not, that's easy: First select the Plain Text field (i.e. your Heading field) as the toggle, then choose "not equal to". Keep the value empty, and save. This will keep your target field (i.e. subheading) hidden as long as the toggle field (Heading) is empty.
