### ISSUE TITLE
Error - Not able to access CP - Trying to get property of non-object 

### ISSUE THREAD

**Issue by superflausch** [mmikkel/Reasons-Craft#2]
Since today I get the following error message in the Craft CP.

2015/06/08 11:49:52 [error] [php] Trying to get property of non-object (/......./plugins/reasons/services/ReasonsService.php:147)

I have no clue what I did to provoke it. Last action was to delate a field, which was not setup to use Reasons at all (I have no Rules for Reason at all at the moment).

Also I'm not able to access the CP at all. I was able to manually remove the reasons plugin folder, which allows me to access the CP again. What would I have to uninstall manually (DB entries)? Or do you have an idea what the error could have triggered? Let me know what additional info I could provide. I would use Reasons if it would work again. Cheers.

**Comment by mmikkel** [comment]
Thanks for the detailed report - I'll look into it ASAP!

**Comment by superflausch** [comment]
Thanks a lot.

I think I found the issue for the error. I had a field defined with a custom field-type, where I already uninstalled the corresponding plugin. Therefore I had an invalid field-type setup, which seems to cause the error. Removing the field solved the issue for me.

**Comment by mmikkel** [comment]
@superflausch, I just pushed v. 0.1.2 – could you check if this resolves your issue?

Unfortunately, I can't reproduce your problem so I'm not entirely sure what would cause it. Are you using any custom fieldtypes?

**Comment by mmikkel** [comment]
Oh, just noticed your latest comment :D

Right on, thanks for getting back to me – great to know what caused it. The hotfix I just added makes sure it won't happen again.

**Comment by superflausch** [comment]
Great, thank you very much.
