### ISSUE TITLE
Implement User Group specific conditionals

### ISSUE THREAD

**Issue by mmikkel** [mmikkel/Reasons-Craft#20]
It'd be great if it was possible to create conditionals for specific fields based on a) the currently logged in user's user group(s) and b) the user group(s) for the User element being edited.

**Comment by idahotallpaul** [comment]
+1. Just got off the phone with a client requesting inputs be hidden based on user group. Is this in the pipeline? ETA?

Thanks.

**Comment by mmikkel** [comment]
Hi @idahotallpaul – currently it's a feature I'd like to add, nothing more. It's not super difficult to do, so I'd say the chances of it happening are pretty good. Unfortunately I can't give you an ETA, but if it happens it's probably going to be a good month or two, as I've got a lot of client work right now. Sorry for not being more specific, but I'd really like to avoid promising a thing and then not deliver.

**Comment by idahotallpaul** [comment]
Roger that! Thanks!

**Comment by mmikkel** [comment]
If you need something like this right now, I'd suggest taking a look at Lindsey DiLoreto's [CP User Group plugin](https://github.com/lindseydiloreto/craft-cpusergroup), which will add classnames based on user groups to the `<body>` tag – making it possible to use CSS to hide certain fields for certain user groups.

**Comment by khalwat** [comment]
This would be really useful.
