### ISSUE TITLE
Feature request: Enable if X field has content

### ISSUE THREAD

**Issue by cballenar** [mmikkel/Reasons-Craft#22]
Great plugin but for some reason this feature seemed like a no brainer to me. Give the ability to use any field as a toggle field if it has content.

Example:
- If field _Cover Image_ has an image selected, activate the fields _Highlight_, and _Select Crop Ratio_.
- The option in the conditional dropdown would be "Is empty / Has content" or something alike.

Anyone working on this or something like this? Is there anything that would prevent us from making it possible?

I'm gonna try to add this capability. It doesn't seem like it would be too difficult but I'm not very familiar with PHP.

**Comment by cballenar** [comment]
Nevermind... I was talking out of my butt and I'm completely lost as to how to do this... :P

**Comment by mmikkel** [comment]
Hi @cballenar, thanks for contributing! The feature you're asking for would be a good one – it's actually been brought up before, check out issue #21.

It'll probably happen at some point, but as with most things feature request-y, I'm hesitant to actually give any kind of ETA :)

**Comment by cballenar** [comment]
Oh, nice. I didn't see that. 

I completely get what you're saying. I'll look over the code a little more and if I make any progress I'll be sharing it here.

Thanks!

**Comment by mmikkel** [comment]
Hello @cballenar – it took a while, but [Reasons 1.0.5](https://github.com/mmikkel/Reasons-Craft/releases/tag/v.1.0.5) adds all built-in relational fieldtypes (Entries, Assets, Categories, Tags and Users) as toggle fields, with simple empty/not empty statements. Hope it proves useful to you!

**Comment by cballenar** [comment]
Awesome! Thanks a lot! I'll try it out asap
