### ISSUE TITLE
Fields in Matrix blocks getting hidden

### ISSUE THREAD

**Issue by benjamminf** [mmikkel/Reasons-Craft#23]
Situation: Matrix block has a field with handle `fieldHandle`. There's some other global field that also has the handle `fieldHandle`. The Matrix field and global field are added to the same field layout tab. Reason rules added to the global `fieldHandle` field will also affect the `fieldHandle` field in the Matrix block.

Pretty edge-casey and trivial to work around but thought I'd report it anyway :)

**Comment by mmikkel** [comment]
Ouch, thanks for the report @benjamminf, and sorry for the late reply. Sounds easy enough to fix – will get to it shorty :)

**Comment by mmikkel** [comment]
Should be fixed in v. 1.0.4. Sorry for the delay, @benjamminf.
