### ISSUE TITLE
Support Solspace Calendar plugin

### ISSUE THREAD

**Issue by zizther** [mmikkel/Reasons-Craft#24]
Solspace have released a Calendar plugin.

The way it works is it has its own field type selector, by default this does not have the option to have Reasons in a fields option.

**Comment by mmikkel** [comment]
Thanks for contributing, @zizther! No promises, but I'll see what I can do :)

**Comment by mmikkel** [comment]
Hello @zizther – full support for Solspace Calendar Events and the Solspace Calendar Events fieldtype just landed with [v.1.0.5](https://github.com/mmikkel/Reasons-Craft/releases/tag/v.1.0.5).

The fieldtype conditional is a simple empty/not empty statement; same as the rest of the stock relational fieldtypes (Entries, Assets etc).

Let me know if you have any additional input or requests, and thanks again for contributing.

**Comment by zizther** [comment]
Amazing. Thanks fir the effort.
Looking forward to having this useful feature.

N
