### ISSUE TITLE
Keyboard Toggle

### ISSUE THREAD

**Issue by billythekid** [mmikkel/Reasons-Craft#25]
Navigating to a lightswitch field which holds a rule by using tab, then hitting space to toggle the switch doesn't action the view conditions. I presume an event listener isn't firing.

**Comment by mmikkel** [comment]
Thanks for reporting, @billythekid – I'll investigate ASAP.

**Comment by mmikkel** [comment]
Fixed in version [1.0.6](https://github.com/mmikkel/Reasons-Craft/releases/tag/v.1.0.6). Thanks for reporting!
