### ISSUE TITLE
Checkboxes are not working. Multi-select does not work if multiple items are selected.

### ISSUE THREAD

**Issue by idahotallpaul** [mmikkel/Reasons-Craft#3]
I have a list of business categories. Businesses can belong to more than one category, so for example, one business can be a venue and a restaurant. So I need to be able to display additional fields based on each category selected. For example, if "venue" is selected, then display a table field to enter details about the different rooms in the venue. If "restaurant" is selected, display a dropdown of different types of restaurant to choose from.

I tried checkboxes, and wether it was one checkbox or many, I could not get fields to be displayed based on what was selected.

I tried a multi-select with the same categories, and if you choose a single category, the inputs would be revealed. Select multiple and the interface would be hidden.

Not sure why the checkbox doesn't work, but on the multi-select, my guess is it's checking to see if the value for the field "businessType" equals "venue". When only venue is selected, it evals to true, but if it equals "venue, restaurant" it is false. Perhaps it should check to see if the array _includes_ "venue"?

Thanks.

**Comment by mmikkel** [comment]
Thanks a bunch for reporting! I'll look into your issue ASAP.

**Comment by idahotallpaul** [comment]
You bet. How far off are you from having categories implemented? That would be the ideal case for me, as categorization of businesses and filtering by those categories of is the ultimate goal. 

Thanks.

**Comment by mmikkel** [comment]
Relational fields (like Categories, Entries, Tags etc.) as "toggle fields" is doable, though it isn't something I've begun implementing or even looked into.

Unfortunately I haven't been able to commit much time to Reasons since making the initial public release (0.1) available. When I do, I'm going to focus on Matrix support (as in Reasons within Matrix) and a few other todos.

I appreciate the feature request though - it will probably make it in some day although unfortunately I can't give an ETA.

**Comment by mmikkel** [comment]
Hello @idahotallpaul – sorry for the big delay, but this should be sorted now.

Having Reasons check if the multi-select or checkboxes field _includes_ a value would be the wrong behaviour in my opinion, but please note that both Checkboxes and Multi-select fields now render as a multiselect input in the conditionals builder (see http://cly.mmikkel.no/image/392k2U0Q3E0z), making it possible to properly configure which values should trigger the target field.

Thanks again for reporting!
