### ISSUE TITLE
Using AND conditional not triggering show hide

### ISSUE THREAD

**Issue by swixpop** [mmikkel/Reasons-Craft#30]
Here is my setup:
Lightswitch 1
--Text field (show if Lightswitch 1 is on) works as expected
--Lightswitch 2 (show if Lightswitch 2 is on) works as expected
--Number field (show if Lightswitch 1 is on AND Lightswitch 2 is on) doesn't work

If I turn on Lightswitch 1 and Lightswitch 2 is in the off state the Number field doesn't show (good). I turn on Lightswitch 2 and the Number field still doesn't show (bad). Now if I turn Lightswtich 1 off and on again, the Number field does how (good but shouldn't require this step).

Any thoughts?

**Comment by mmikkel** [comment]
Thanks for contributing @swixpop! Sounds like a bug. I'll take a look at it ASAP.

**Comment by mmikkel** [comment]
Hi @swixpop – this should be fixed in [v. 1.0.8](https://github.com/mmikkel/Reasons-Craft/releases/tag/v.1.0.8). Thanks for reporting!
