### ISSUE TITLE
Support for the Charge plugin [Feature Request]

### ISSUE THREAD

**Issue by tofirius** [mmikkel/Reasons-Craft#31]
In Charge Pro, a user is allowed to use custom Craft fields within the [Charge plugin](http://squarebit.co.uk/software/craft/charge/usage/features/fields)

`CP->Charge->Settings->Fields`

It would be helpful to have Reason flow into that Fields section of Charge to allow for conditional validation. Thanks so much!

**Comment by mmikkel** [comment]
Hi @tofirius – thank you for contributing, and sorry for the late reply. Unfortunately, I've recently [decided to end development on Reasons](https://github.com/mmikkel/Reasons-Craft/wiki/Statement-on-Reasons-2,-Matrix-and-Craft-3), so any new features or changes to current features won't happen.
