### ISSUE TITLE
Use preparse as toggle field

### ISSUE THREAD

**Issue by Kashkin** [mmikkel/Reasons-Craft#33]
Would it be possible to use [Preparse](https://github.com/aelvan/Preparse-Field-Craft) as a toggle field? I realise it may only show fields after a save, but I can still think of use-cases.

**Comment by mmikkel** [comment]
Hi @Kashkin – thanks you for contributing, and sorry for the late reply. Nope, Preparse won't work with the current version of Reasons. Unfortunately, I've recently [decided to end development on Reasons](https://github.com/mmikkel/Reasons-Craft/wiki/Statement-on-Reasons-2,-Matrix-and-Craft-3), so any new features or changes to current features won't happen.
