### ISSUE TITLE
Add my own element type?

### ISSUE THREAD

**Issue by Nav33d** [mmikkel/Reasons-Craft#34]
Hi,

Is it possible to add my own element types to Reasons?

Many thanks

**Comment by mmikkel** [comment]
Hi @Nav33d – thank you for contributing, and sorry for the late reply. Unfortunately, I've recently [decided to end development on Reasons](https://github.com/mmikkel/Reasons-Craft/wiki/Statement-on-Reasons-2,-Matrix-and-Craft-3), so any new features or changes to current features won't happen.
