### ISSUE TITLE
Add third statement for checkboxes "is selected" not the same as "is equal to"

### ISSUE THREAD

**Issue by TomDeSmet** [mmikkel/Reasons-Craft#35]
If you have a checkbox field and you want another field to be visible based on the selected criteria, there should be a third statement "is selected".

Because now with the "equal to" statement, you have to add a conditional for every possible combination of checkboxes selected. Which obviously is a no go when you have more than 3 checkboxes and when there's a possibility in the future you might alter the field to have more.

A solution would be to check if the conditional is part of the selected checkboxes array instead of checking for the exact same value.

Is this something that's easily written? Because I really really need this quick :) Else I need to rethink my complete setup :(

**Comment by mmikkel** [comment]
Hi @TomDeSmet – thank you for contributing, and sorry for the late reply. Unfortunately, I've recently [decided to end development on Reasons](https://github.com/mmikkel/Reasons-Craft/wiki/Statement-on-Reasons-2,-Matrix-and-Craft-3), so any new features or changes to current features won't happen.
