### ISSUE TITLE
Category condition: only allows to pick "not empty" instead of actual category

### ISSUE THREAD

**Issue by yananym** [mmikkel/Reasons-Craft#36]
Hi!

Thank you, very useful plugin!
I am trying to show a specific field for entries with system category "Team", but i have other system categories.
The condition only  lets me select "System Category" "equals to" "not empty".
But i would like to select "Team". Is there a way to do that or would that have to be a feature request?

Thanks!

**Comment by mmikkel** [comment]
Hi @yananym – thank you for contributing, and sorry for the late reply. Unfortunately, I've recently [decided to end development on Reasons](https://github.com/mmikkel/Reasons-Craft/wiki/Statement-on-Reasons-2,-Matrix-and-Craft-3), so any new features or changes to current features won't happen.
