### ISSUE TITLE
Leaking data on login screen

### ISSUE THREAD

**Issue by evanwarner** [mmikkel/Reasons-Craft#37]
Just like mmikkel/CpSortableCustomColumns-Craft#11 which I just opened, this plugin also dumps a big JSON string to the DOM, but doesn't check to make sure a CP user is logged in.

Anonymous users can hit the login screen and see all the admin data Reasons uses. This plugin reveals even more info than the Sortable Columns plugin though, showing all the settings on each field.

**Comment by mmikkel** [comment]
Hi @evanwarner – thanks for contributing. Good catch, easy fix – download [Reasons v. 1.0.9](https://github.com/mmikkel/Reasons-Craft/releases/tag/v.1.0.9) for a leakage free experience.
