### ISSUE TITLE
Reasons support with the latest version of Craft 2 (2.6.3007)

### ISSUE THREAD

**Issue by Moorst** [mmikkel/Reasons-Craft#38]
Since updating to the latest version of Craft, reasons has stopped working. All the fields that previously had conditions set are now showing by default and editing the section field layout the option to add conditionals isn't there.

**Comment by EtienneTLM** [comment]
Same for me :(

**Comment by theskyfloor** [comment]
The version of jQuery used in control panel changed... Are there any errors in the browser console?

**Comment by kblizeck** [comment]
No errors in the console :(

**Comment by mmikkel** [comment]
Hey, thanks for the heads up @Moorst – I'll look into it ASAP.

**Comment by mmikkel** [comment]
@Moorst @EtienneTLM @theskyfloor @kblizeck 

Just published [Reasons 1.0.11](https://github.com/mmikkel/Reasons-Craft/releases/tag/v.1.0.11) – everything works fine in Craft 2.6.3007 on my end now; if anyone can test this release and let me know if it fixes your issues, that'd be great :)

**Comment by EtienneTLM** [comment]
Everything seem to be ok for my part with the update to 1.0.11. Thank you very much!

**Comment by mmikkel** [comment]
Awesome, thanks for the reply @EtienneTLM.

**Comment by Moorst** [comment]
Apologies for the delayed response. The plugin is now working fine for me too, Thanks @mmikkel!

**Comment by kblizeck** [comment]
Thanks @mmikkel - everything's working great!

**Comment by mmikkel** [comment]
Thanks everyone for replying!
