### ISSUE TITLE
Any alternative to Reasons?

### ISSUE THREAD

**Issue by zzseba78** [mmikkel/Reasons-Craft#39]
Since Reasons stop active development and doesn´t work with current version, any alternative?

**Comment by mmikkel** [comment]
@zzseba78 I'm aware that Reasons doesn't work w/ the latest version of Craft 2.x; ideally I want it to keep working for the duration of Craft 2's lifespan so I'm looking into it.

Don't think there's any alternative to Reasons, but P&T did promise that field layout conditionals would make it into core at some point...

**Comment by mmikkel** [comment]
Hey @zzseba78 – I just published [Reasons 1.0.11](https://github.com/mmikkel/Reasons-Craft/releases/tag/v.1.0.11) and everything works fine in Craft 2.6.3007 on my end now; if you can test this release and let me know if it fixes your issues, that'd be great :)
