### ISSUE TITLE
Matrix Fields

### ISSUE THREAD

**Issue by jacobgraf** [mmikkel/Reasons-Craft#4]
Would love to see this add-on work with fields within a Matrix field! :-)

**Comment by chasegiunta** [comment]
+1 For sure! And Super Table :-)

**Comment by akukral** [comment]
+1 Indeed!

**Comment by mmikkel** [comment]
Matrix support is in the works. I've been swamped lately, though – can't give an ETA, unfortunately. Thanks for the interest, though!

**Comment by kaspar-allenbach** [comment]
+1

**Comment by menberg** [comment]
This would be huge. Matrix with conditionals... imagine!

**Comment by josephbergdoll** [comment]
+1

**Comment by sammorrisdesign-zz** [comment]
+1 Would be perfect for the project we're working on now

**Comment by samlous** [comment]
When using the plugin "NEO", it is possible to use Reasons in a Matrix 👯 
Maybe a good alternative while the feature is nog yet available.

**Comment by joepagan** [comment]
Indeed this would be ace! Any updates now we're in 2017?
