### ISSUE TITLE
Flickering bug when using inside fieldtype layout of a Neo field

### ISSUE THREAD

**Issue by steveooo9** [mmikkel/Reasons-Craft#40]
Since the newest version, things start to flicker when inside a Neo field.
Inside other fields, it seems to work so there is probably some JavaScript issue.

**Comment by mmikkel** [comment]
Hi @steveooo9, thanks for contributing!

This is probably something that needs to be fixed in Neo, not Reasons, so I suggest creating an issue over at the Neo repo.
