### ISSUE TITLE
No conditional fields in Craft for at least another year (or more)

### ISSUE THREAD

**Issue by lindseydiloreto** [mmikkel/Reasons-Craft#42]
According to [this slide](https://speakerdeck.com/brandonkelly/future-of-craft?slide=24), Craft won't support conditional fields until Craft 4. At this moment in time, Craft 3.1 has just been released, and Craft 4 is _at least_ a year away. Taking into account that most software ships later than expected, it's fully possible that Craft 4 won't ship for another 18 - 24 months.

Would you consider reconsidering your decision to shelve this plugin?  ❤️ 

It's clearly beloved (with nearly 250 stars on Github), and would be welcome into the modern Craft ecosystem with open arms. There's no denying the demand is there!

Hell, you could even charge for it... you would get plenty of buyers, I'd be first in line!

![takemymoney](https://user-images.githubusercontent.com/5309692/52311892-739ee000-295d-11e9-8dce-3e724b646c64.jpg)

**Comment by mmikkel** [comment]
Hi @lindseydiloreto – yeah, the conditionals stuff and other field layout improvements being pushed to Craft 4 was, honestly, both unexpected and quite disappointing, especially since I've been determined since 2017 to **not** port Reasons due to this feature being slated for 3.x 🙄 

I do appreciate the interest in this plugin, and you know – never say never – but for my own sanity's sake I'm not going to make any promises. TL;DR: Don't count on it, sorry 😄 

_If_ I ported Reasons to Craft 3, at this point it'd have to be a complete rewrite and honestly, that's quite a bit of work that I'm not sure I'd even find the time to do, currently.

There's nothing stopping somebody else from doing it, though! 🚀

**Comment by lindseydiloreto** [comment]
Bummer. I'm also swamped, or I'd definitely consider doing it myself.

Fingers crossed somebody takes on this challenge! 🤞

**Comment by outline4** [comment]
Please! Please! Please!

**Comment by missmatsuko** [comment]
There's a Craft 3 plugin called Conditions which seems to be based on Reasons and adds the same functionality:
https://plugins.craftcms.com/conditions

**Comment by outline4** [comment]
Hi, I already saw this, but it does not seem to be stable…

**Comment by mmikkel** [comment]
Sorry @outline4 – at this point, I will definitely not port Reasons to Craft 3.

**Comment by lindseydiloreto** [comment]
An unfortunate, but understandable position @mmikkel.

Thanks for building such an awesome plugin in the first place! 🍺

**Comment by mmikkel** [comment]
@lindseydiloreto Surprise! I wasn't gonna do it, but [then I did](https://github.com/mmikkel/Reasons-Craft3).

**Comment by lindseydiloreto** [comment]
![awesome-min](https://user-images.githubusercontent.com/5309692/83688904-f57b3980-a5a2-11ea-9234-8bfda99c6549.gif)

Whaaaaa??? That's amazing, better late than never! Good timing, in fact... there was just some chatter on Discord that C4 may be delayed even further.

@mmikkel Thanks for taking the time and effort to port this over to C3 (and keeping it free)! 🍺

**Comment by mmikkel** [comment]
@lindseydiloreto Yeah, I mostly decided to finally bring it over to make it easier to upgrade some Craft 2 sites. I guess a lot of people have already upgraded most of their Craft 2 sites to Craft 3, and have found workarounds in lieu of Reasons... so I don't expect to see a huge popularity for it at this point, which is totally fine :)

As stated in the readme, I'd actually also recommend not using Reasons 2 for new Craft 3 projects. I do plan on maintaining it for upcoming 3.x releases, but... compared to the Craft 2 era, Pixel & Tonic have been tweaking the Control Panel _alot_, for every Craft 3 point release (sometimes even in a patch release). So any plugin that depends on JavaScript hacks and markup, like Reasons, can break at any time, and must be considered unstable – and I think it'd be unethical to charge for a plugin like that, unless you can absolutely guarantee that you'll be able to deal with the support and/or put out patch releases quickly if it happens (which I can't promise; I'm just a single person).
