### ISSUE TITLE
Add Craft cms 3.x support. 

### ISSUE THREAD

**Issue by insaurabh** [mmikkel/Reasons-Craft#43]
Is there any planning to upgrade this plugin for craft cms3.x ?

Thank you.

**Comment by mmikkel** [comment]
Hi @maddyBoy – no plans currently, sorry. Field layout conditionals in core was planned for Craft 3.2, but was recently pushed to Craft 4 (ETA sometime in 2020).

Also see https://github.com/mmikkel/Reasons-Craft/wiki/Statement-on-Reasons-2,-Matrix-and-Craft-3
