### ISSUE TITLE
No Toggle Fields available

### ISSUE THREAD

**Issue by bwatabu** [mmikkel/Reasons-Craft#44]
Craft CMS 3.1.30
Conditions 1.0.3

After adding a Lightswitch field ("Extended Layout" is the Lightswitch in my screenshot. Other fields are Matrix and Redactor), I am unable to add Rules in the pop-up window when clicking the "Edit Conditionals" link. The message says "No toggle Fields available". Any solutions? 

<img width="604" alt="Screen Shot 2019-06-15 at 3 28 24 PM" src="https://user-images.githubusercontent.com/5335129/59557971-c24f2d00-8f82-11e9-8f61-817798d009e2.png">

<img width="611" alt="Screen Shot 2019-06-15 at 3 32 02 PM" src="https://user-images.githubusercontent.com/5335129/59557980-edd21780-8f82-11e9-8fac-4681b2060ae5.png">

<img width="552" alt="Screen Shot 2019-06-15 at 3 30 14 PM" src="https://user-images.githubusercontent.com/5335129/59557981-f4f92580-8f82-11e9-99db-2e384dfd74de.png">

**Comment by mmikkel** [comment]
Hi @bwatabu, this is the repo for the Craft 2 plugin Reasons – [Conditions](https://github.com/MilkshakeStudio/craft-conditions) for Craft 3 is a different plugin, which I'm not involved in.
