### ISSUE TITLE
Radio buttons does not work

### ISSUE THREAD

**Issue by migmake** [mmikkel/Reasons-Craft#5]
Got radio buttons and a field appaearing for a value of that radio button.
But does not appear.
Here screens.
![screen shot 2015-08-18 at 05 32 25](https://cloud.githubusercontent.com/assets/3531623/9329936/8cde8866-456a-11e5-8964-1b3f0f99ced4.jpg)
![screen shot 2015-08-18 at 05 31 35](https://cloud.githubusercontent.com/assets/3531623/9329938/8ce1dff2-456a-11e5-9c45-5c5ca67f16e7.jpg)
![screen shot 2015-08-18 at 05 31 45](https://cloud.githubusercontent.com/assets/3531623/9329937/8ce18106-456a-11e5-8a6c-34ac479846c8.jpg)

**Comment by migmake** [comment]
Work fine on a lightswitch thats true. But not for radio buttons...

**Comment by mmikkel** [comment]
Thank you for the bug report, @migswd. I'll get it sorted ASAP.
