### ISSUE TITLE
Conditionally require fields

### ISSUE THREAD

**Issue by davist11** [mmikkel/Reasons-Craft#8]
It would be really could if you could conditionally require fields that are hidden/shown with Reasons.

**Comment by mmikkel** [comment]
Hey @davist11, thanks for contributing! Could you explain in a little more detail what you mean by "conditionally require", perhaps with a use case/example? Not sure I follow :)

**Comment by davist11** [comment]
Sure! So when you are managing conditionals for each field, it would be great if there was also a way to say "require" this field.

Let's say I have the following fields:
- Include Contact Info (lightswitch)
- Phone Number (plain text)

Then, if I manage the conditionals for phone number, I would say to show this field if **Include Contact Info** is equal to **on**. I would also like to say require  this field if **Include Contact Info** is equal to **on**.

**Comment by mmikkel** [comment]
Thanks for the explanation @davist11 – I understand now. I'm not sure how easy it would be to make a non-required field required on the fly, but it could easily be "faked" with jQuery. An alternative (and in my mind, slightly better) approach would be to have the field set as required in the first place, and just "override" the requirement somehow if the field is hidden when the entry is saved – though that sounds harder to implement.

Can't promise you anything, but I'll label this as an enhancement and put it on the roadmap!

**Comment by davist11** [comment]
Yup, I forked the plugin and started down the latter approach you listed above during some free time. But then I got busy and didn't get very far!

**Comment by mmikkel** [comment]
Cool – I _love_ pull requests, so I hope you find the time!

**Comment by mmikkel** [comment]
The way I'd do this (the second approach, mind you) is probably to add a hidden input field with jQuery to the entry edit form, containing the IDs of any currently hidden fields. When the entry is saved, it'd be easy to pick up those IDs w/ `craft()->request->getPost('reasonsHiddenFields')` or the like in the `onEntrySave` handler. Then you'd just need to figure out a way to make Craft treat those fields as non-required, even if they actually are – which is where I'm currently drawing a blank, but it could probably be done.

The more I think about it, this would actually be a really good feature. As it stands, Reasons will actually prevent you from being able to save an entry if a required field has been hidden – which is kind of dumb, and I think that if you went to the trouble of creating conditionals for said field, it logically follows that a "required" property should be probably be void.

**Comment by davist11** [comment]
Ohh that's smart, didn't even think to approach it that way.

**Comment by mmikkel** [comment]
I think it's going to be really difficult to override or change the `required` property for the model within the event handler, though. Perhaps the best bet is to give Craft some kind of default dummy value for the fields in question, though that wouldn't be without ramifications. Either that, or you could set the `validateContent` property to false and run your own validation on the required, non-hidden fields... Could get messy real quick! :D

**Comment by lboaretto** [comment]
I needed to do the same thing... Validate a field only if it was selected via Lightswitch (on/off).

I had to leave the field open without validation, but would like to see it working. Someone already did it work?
