### ISSUE TITLE
Feature Request: Reasons usable in User Fields

### ISSUE THREAD

**Issue by GeorgeD121** [mmikkel/Reasons-Craft#9]
Would it be possible to add functionality to user fields? 

It could potentially be very beneficial to keep a slightly more concrete separation of fields between user types than just the groups, as at the moment all users have the same fields in craft so this could allow admins to break fields up slightly.

**Comment by mmikkel** [comment]
Hello @GeorgeD121 – thanks for contributing. Its possible to do, and the goal is to support all element types eventually. Can't give you an ETA, but I'll label it as an enhancement and will get to it sooner or later :)

**Comment by mmikkel** [comment]
This is in development (as well as support for all the other native element types). I hope to have it out some time in December.

**Comment by GeorgeD121** [comment]
Awesome!

**Comment by mmikkel** [comment]
Reasons now works for User fields (as well as all other native element types) – check out version 1.0.

**Comment by GeorgeD121** [comment]
Awesome, thank you for the update. I'm just looking now, would it be
possible to make the user group a conditional? So only show this field if
they belong to a certain group?

**Comment by mmikkel** [comment]
Hey @GeorgeD121, it's not possible currently and it's not really something Reasons was designed to do (i.e. add conditionals not based on a "toggle" field's value). It'd definitely be useful, though, so I'll give it a thought and try to come up with a solution.

Pertaining to users, though, there are multiple possible nice-to-haves. For one, it'd be nice to be able to have a field only display on a user's profile if that particular user was in a certain user group (this is what I think you're requesting?). However, it'd also be cool to have a field only display if the _current user_ was in a certain user group (this could be applied to any field layout, not only user fields/profiles).

In implementing both of these, I'm actually more concerned about the Reasons UI than parsing/applying the conditionals. One idea that comes to mind, is to add some options to bottom of the "toggle field" dropdown in the conditionals builder modal, such as

(Current user is) (in group/not in group/admin) (list of user groups) _displays for all element types_
(User is) (in group/not in group/admin) (list of user groups) _only displays when editing the User profile field layout_

If I implement something like that, other types of conditionals could possibly be added, too, such as only displaying a field if the site is in `devMode`, if the element is in a certain locale, etc.

Appreciate any and all thoughts on the matter – thanks!

**Comment by GeorgeD121** [comment]
Hey,

You're exactly right on what I was requesting, "For one, it'd be nice to be
able to have a field only display on a user's profile if that particular
user was in a certain user group (this is what I think you're requesting?)".

The display if current user is a certain user group, would be awesome. It
could come in handy in so many cases, especially for restricting clients
within entries in the CMS.

I think adding options to the conditional builder modal could be a good
solution if the UI is a concern. As that modal has a good amount of white
space to play with as it stands, so you may be able to fit a few more
fields in there without confusing the experience.

Great work on the plugin! Brilliant response to the feedback, very
much appreciated.

**Comment by mmikkel** [comment]
Thanks for the nice words, @GeorgeD121 – much appreciated. I'll think this through a bit and will update this issue if I decide to do something about it one way or the other :)

**Comment by chasegiunta** [comment]
Just want to add a little +1 to this... I manage a site with multiple user groups, where there are massive amounts of different fields for each user group. It's quite the headache to figure out which fields belong to which type of user, not to mention, easily figuring which type (user group) of user you're currently viewing. As a workaround, Lindsey Diloretto's `craft-cpusergroup` plugin has the capability to handle this (as well as showing/hiding based on the user who is currently viewing) but it's a PITA to actually set up manually through .classes. Reasons would be a very welcome addition to solve this problem. :) Nice job so far @mmikkel !

**Comment by mmikkel** [comment]
Appreciate the input, @ChaseGiunta – I'm aware of Lindsey's plugin though I agree that hiding/displaying fields according to user groups could probably be nicely solved with Reasons. No promises, but I'm definitely considering viable ways to do this :)
